apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: blc_api
  description: 
spec:
  type: api
  lifecycle: production
  owner: growth-team
  system: core
  dependsOn:
    - resource:default/mks-cluster
  providesApis:
    - artist2-api
